### ISSUE TITLE
Dynamic Fonts

### ISSUE THREAD

**Issue by GEverding** [skippbox/cabin-issues#10]
Hi, love the app. I use dynamic fonts on iOS (Accessibility Option) and the headers and labels aren't scaling appropriately. 
![slack for ios upload png](https://cloud.githubusercontent.com/assets/1377740/17874078/6a6bdb34-6897-11e6-86f9-2a3745a87d18.jpeg)

**Comment by runseb** [comment]
Hi, thanks for filing this issue. Indeed, we did not test this. Hopefullt we will be able to fix it quickly.

Thanks again for reporting it,

**Comment by GEverding** [comment]
Hey, is this issues still being worked on?

**Comment by sebgoa** [comment]
It should be much better in the latest version, did you update ?

**Comment by GEverding** [comment]
It is better with the latest update. It's great to see. 

--
Garrett




On Tue, Nov 22, 2016 at 3:01 AM -0500, "sebgoa" <notifications@github.com> wrote:












It should be much better in the latest version, did you update ?

**Comment by sebgoa** [comment]
ok we will try to keep improving this, but can we close this for now ?

**Comment by sebgoa** [comment]
This issue was moved to bitnami/cabin#13
