### ISSUE TITLE
sometimes cabin doesn't display nodes

### ISSUE THREAD

**Issue by ngtuna** [skippbox/cabin-issues#11]
I found sometimes cabin doesn't display nodes info. Like this one:

![cabin](https://cloud.githubusercontent.com/assets/1963463/17918522/d547ce96-69ef-11e6-8cd3-b052c63a1bf6.jpg)

**Comment by runseb** [comment]
That's because you switched namespace in one of your views, and since nodes are not namespaced Cabin is not seeing them in the default ns.

We noticed it as well..

**Comment by ngtuna** [comment]
That's right. Switching to all namespaces makes nodes appear again.
