### ISSUE TITLE
Keyboard covers entry box when executing commands in shells

### ISSUE THREAD

**Issue by davidreuss** [skippbox/cabin-issues#12]
Hello,

Congratulations on cabin, it's great, and feels very polished.

When executing commands in a container, the keyboard covers the entry box, so you can't see what you've already typed. That's a shame, and probably just a simple bug.

No idea if this is the correct place to submit this, but given the repos name, i'm guessing it is.

Observed on iPhone 5S, running cabin `0.1.0` (iOS is `9.3.2`).

**Comment by runseb** [comment]
Hi @davidreuss yes definitely the right place and thanks for the feedback.

We noticed it too, should be an easy fix indeed.

cheers

**Comment by sebgoa** [comment]
Fixed in latest release
