### ISSUE TITLE
App crashing when trying to add new services.

### ISSUE THREAD

**Issue by khoiln** [skippbox/cabin-issues#14]
Hi guys, 
I'm trying out the Cabin app, overall it's great 👍. But I found out a crash bug :

![14678041_1655163848108980_553363629_o](https://cloud.githubusercontent.com/assets/6994441/19418216/cd86d656-93e9-11e6-80e2-d8b993c3a37f.jpg)

The app crashes when I click on the "Add" button for this dummy `https://` hosts 

Device: iPhone 7 Plus
iOS 10.0.1

**Comment by sebgoa** [comment]
Do you have a working cluster ?

**Comment by khoiln** [comment]
I don't actually, I'm just testing out the app, hit the add cluster button and click done immediately, looks like there should be a validation when adding the cluster :P

**Comment by sebgoa** [comment]
yes good point.

if your cluster is not valid, adding a service will fail.

though it should not crash the app.

thanks we will fix it in the next release

**Comment by sebgoa** [comment]
Ok, we added some checks for the URL of the cluster. It avoids setting a really bad URL.
