### ISSUE TITLE
Is cabin open source?

### ISSUE THREAD

**Issue by mdshuai** [skippbox/cabin-issues#15]
cabin for ios is a open source project?
thanks

**Comment by sebgoa** [comment]
Hi, no not yet.

we are talking about it though.

**Comment by mdshuai** [comment]
@sebgoa thank you!

**Comment by sebgoa** [comment]
Hi, I am working on this, hoping to open source it in the next couple months.

**Comment by firehist** [comment]
Hey guys, awesome work there!
Is there any updates on this issue?
🚀 💪

**Comment by sebgoa** [comment]
@firehist couple more weeks, I swear.

**Comment by firehist** [comment]
Okay sir, good luck.
We look forward to contributing!

**Comment by sebgoa** [comment]
This issue was moved to bitnami/cabin#11
