### ISSUE TITLE
Certificate Auth

### ISSUE THREAD

**Issue by ccatlett2000** [skippbox/cabin-issues#19]
Hello, I have a Kubernetes cluster that I can't access because cabin doesn't support cert auth. Could this be added?

**Comment by sebgoa** [comment]
You want client certificates for auth, instead of token or basic auth ?

If yes, how do you envision do provide the certs in the app ?

We have a solution in dev, but it requires putting the cert somewhere it can be downloaded and would be insecure if done over the public internet.

**Comment by ccatlett2000** [comment]
I don't intend for the app to have to deal with getting the cert securely to the device, I can do that myself. Obviously just dropping it on a webserver somewhere isn't secure, but that is outside of cabin's control.

**Comment by bharris47** [comment]
Cert auth is working for me. I just downloaded the cert from Google Drive and installed it.

**Comment by sebgoa** [comment]
This issue was moved to bitnami/cabin#8
