### ISSUE TITLE
No ability to list Horizontal Pod Autoscalers.

### ISSUE THREAD

**Issue by bharris47** [skippbox/cabin-issues#22]
Would be nice to be able to view and edit the current state of `hpa`s (cpu percent, min, max, etc).

**Comment by bharris47** [comment]
Changing the max would be helpful. Being able to see current CPU usage within them would be great. It would also be really useful to be able to create an HPA for a deployment.

**Comment by sebgoa** [comment]
ok thanks , we will slate that for a new release cc/ @kemcake

**Comment by CelsoSantos** [comment]
I too would very much appreciate this functionality

**Comment by sebgoa** [comment]
ok, we will most likely open source cabin, so stay tune...

**Comment by sebgoa** [comment]
This issue was moved to bitnami/cabin#5
