### ISSUE TITLE
Unable to add cluster running in Google Container Engine 

### ISSUE THREAD

**Issue by Jacobh2** [skippbox/cabin-issues#23]
I've tried to reinstall the app, cleared the cache and data and I still run into this problem. 

When I choose to add a GKE cluster, it asks me to select correct Google account, and then it shows me the cluster and that it is up and running. A green notification shows that it has added the cluster successfully, but when I return to the home screen it shows my cluster as "down" when it most certainly is not. 

Selecting the cluster takes me to the page of pods, ns, svc etc but nothing is there. 

What am I missing?

**Comment by sebgoa** [comment]
Thanks for reporting the issue.

Are you on iOS or android ?

can you confirm that you can use `kubectl` to access the cluster from a machine in a different network ?

cc/ @kemcake

**Comment by Jacobh2** [comment]
Hi!

I'm using Android. When I started to test the app I was on version 6.?, but now I'm using 7.0.

Yes, I can access the cluster using `kubectl` on any network.

**Comment by sebgoa** [comment]
ok, we will test for 7.0 and figure it out. it could be the version change.

we will try to fix this asap.

**Comment by sebgoa** [comment]
This issue was moved to bitnami/cabin#4
