### ISSUE TITLE
Can't scroll trough project list 

### ISSUE THREAD

**Issue by GaruGaru** [skippbox/cabin-issues#26]
Can't scroll the project list when adding a cluster using the 'GKE' options

**Comment by sebgoa** [comment]
What platform and what version are you on ? iOS/android

**Comment by GaruGaru** [comment]
I'm on android the scroll isn't working both in landscape and vertical mode

![1](https://user-images.githubusercontent.com/6578583/27768547-dc6fb018-5f16-11e7-859b-4395eb3eb2f9.jpg)

Tried in:
- Samsung galaxy s6
- Zuk z2

**Comment by sebgoa** [comment]
This issue was moved to bitnami/cabin#1
