### ISSUE TITLE
Don't show Charts Store chooser if there's only one

### ISSUE THREAD

**Issue by mboersma** [skippbox/cabin-issues#9]
The Helm kubernetes-charts repo is the default in Cabin, but it's the only entry (unless you add another in settings). So it's confusing that tapping on it in the Deploy screen brings up a no-op chooser with just "Helm Test Store" and "Cancel" as options.

**Comment by runseb** [comment]
ok I see.

When can add a "Add Store" in the chooser which sends you to the add entry in the Settings view.

**Comment by runseb** [comment]
cc/ @kemcake we could do a bit like the namespace creation. Add a "create store" which sends you to the settings/addstore view...

**Comment by runseb** [comment]
This is fixed in the next build.
